FROM base-image
RUN groupadd -g 1000 celery && useradd -u 1000 -g celery -m celery
RUN chown -R celery:celery /app
USER celery
HEALTHCHECK --interval=30s --timeout=5s \
  CMD celery -A better_discovery inspect ping || exit 1

CMD ["celery", "-A", "better_discovery", "worker", "--loglevel=info", "-P", "gevent", "-n", "worker1@%h"]