FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl \ 
    libpq-dev \
    gcc \
    gettext \
    vim \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY better_discovery/ ./better_discovery/
COPY base/ ./base/
COPY api/ ./api