# Generated by Django 5.2 on 2025-05-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_review_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game'),
        ),
    ]
