# Generated by Django 5.2 on 2025-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_game_active_game_avatar_type_game_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnails',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
