# Generated by Django 5.2 on 2025-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_game_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
