# Generated by Django 5.2 on 2025-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_game_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='outdated',
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
    ]
